<div class="reveal">
    <div class="slides">
        <section>
            <h3 class="pb-title">then(..., <i class="fst-italic">onReject</i>) method</h3>
            <section data-auto-animate>
                <pre data-id="code-animation">
                    <code class="language-js bulbs-container-js" data-trim data-line-numbers="|5,14|11-13|17-19|1-5,11-14,17-21"></code>
                </pre>
            </section>
            <section>
                <p>
                    When error is thrown before <b>then(..., <i class="fst-italic">onReject</i>) </b> method it will catch it and won't invoke <b>then()</b> body and pass <i class="fst-italic">undefined</i> to next <b>then()</b>. <b>catch()</b> will intercept second error. If <b>catch()</b> will be before <i class="fst-italic">onReject</i> then <i class="fst-italic">onReject</i> won't intercept error. <b>finally()</b> method will always be invoked both after success or error in Promise chain. Below is how will log from browser console look like.
                </p>
                <pre>
                    <code class="language-plaintext" data-trim>
                        1. setBulbColor
                        Error: Error 1
                        Error: Error 2
                        finally method
                    </code>
                </pre>
            </section>
        </section>
        <section data-background-color="var(--pb-orange-color)">
            <h2>When use onReject inside then() method?</h2>
            <p>In most cases is better to use single <b>catch()</b> at the end of Promise. But such technique can be used as sophisicated 'if' statement. 'if error occours do something and return something else'.</p>
            <button class="pb-next" type="button" onclick="nextBranch('async-3-4-1')">2 go</button>
        </section>
    </div>
</div>
