<div class="reveal">
    <div class="slides">
        <section data-background-color="var(--pb-orange-color)">
            <h2>Promise <b>catch()</b> method</h2>
            <p class="fst-italic">The <b>catch()</b> method returns a Promise and deals with rejected cases only. (...)</p>
            <p class="text-end">
                <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" target="blank">mdn web docs</a>
            </p>
        </section>
        <section>
            <h3 class="pb-title">catch() method</h3>
            <section data-auto-animate>
                <pre data-id="code-animation">
                    <code class="language-js bulbs-container-js" data-trim data-line-numbers="|8|1-8,14-18"></code>
                </pre>
                <button class="fragment pb-next below" type="button" onclick="nextBranch('async-3-3-2')">2 go</button>
            </section>
            <section>
                <p>
                    When error occour it will immediately go to the <b>catch()</b> method which handle errors. Every next line after error will not be invoked. <b>finally()</b> method will always be invoked both after success or error in Promise chain. Below is how will log from browser console look like.
                </p>
                <pre>
                    <code class="language-plaintext" data-trim>
                        1. setBulbColor
                        2. setBulbTime
                        Error: something went wrong
                        finally method
                    </code>
                </pre>
            </section>
        </section>
    </div>
</div>